/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f4",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "on-surface": "#0A2540",
        "on-surface-variant": "#474556",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f0f1f1",
        outline: "#777588",
        "outline-variant": "#c8c4da",
        "surface-tint": "#5036fa",

        primary: "#3904e7",
        "on-primary": "#ffffff",
        "primary-container": "#533afd",
        "on-primary-container": "#ddd9ff",
        "inverse-primary": "#c5c0ff",
        "primary-fixed": "#e3dfff",
        "primary-fixed-dim": "#c5c0ff",
        "on-primary-fixed": "#130067",
        "on-primary-fixed-variant": "#3600e1",

        secondary: "#49607e",
        "on-secondary": "#ffffff",
        "secondary-container": "#c4dcff",
        "on-secondary-container": "#49617f",
        "secondary-fixed": "#d2e4ff",
        "secondary-fixed-dim": "#b0c8eb",
        "on-secondary-fixed": "#001c37",
        "on-secondary-fixed-variant": "#314865",

        tertiary: "#43447b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#5b5c95",
        "on-tertiary-container": "#dcdaff",
        "tertiary-fixed": "#e1dfff",
        "tertiary-fixed-dim": "#c1c1ff",
        "on-tertiary-fixed": "#14134a",
        "on-tertiary-fixed-variant": "#404178",

        error: "#E5484D",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",

        background: "#f9f9f9",
        "on-background": "#1a1c1c",

        muted: "#5E6C84",
        border: "#E6EBF1",
        success: "#81B81A",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1100px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "stack-xs": "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      maxWidth: {
        "container-max": "1100px",
      },
    },
  },
  plugins: [],
};
